ON-15749: Hotfix to handle undefined EFX_NOT_UPSTREAM
Onload does not define EFX_NOT_UPSTREAM, making the required
enum efx_filter_block_kernel_type definition invisible and
causing build-time failure:

src/include/../driver/linux_net/drivers/net/ethernet/sfc/driverlink_api.h:360:13: error: ‘enum efx_filter_block_kernel_type’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
        enum efx_filter_block_kernel_type block);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is a temporary patch in the imported Netdriver that removes
the EFX_NOT_UPSTREAM macro check until we establish the longer-term
approach.