issue #95: move plugins related code under CI_CFG_TCP_OFFLOAD_RECYCLER
The function ci_netif_dmaq_shove_plugin() produces compile warning
on kernels >= 5.18 with gcc >= 10:
error: array subscript 1 is above array bounds of ‘ef_vi[1]’ [-Werror=array-bounds]
  234 |   ef_vi* vi = &ni->nic_hw[intf_i].vis[q_id];
      |                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~

Since it is not used without plugins, lets do not compile it.