linux_resource/ef10: make defines more unique
Add prefixes to the filter defines to avoid potential clashes
with kernel headers names and errors like this:
error: "IP_PROTOCOL" redefined [-Werror]