aarch64: fix kernel build with gcc-10
gcc-10 turns on outline atomics by default and causes errors like:
ERROR: "__aarch64_ldset4_acq_rel" undefined!

Disable the use of the out-of-line functions on aarch64 by compiling
with -mno-outline-atomics.