build: fix missing-prototypes errors
Linux-6.8 enables -Wmissing-declarations -Wmissing-prototypes globally,
causing errors like:
"src/lib/citools/buddy.c:190:6: error: no previous prototype for ‘ci_buddy_validate’ [-Werror=missing-prototypes]"
and many others.

Since there are too many such places in Onload, the patch just disables
the options.

Signed-off-by: Sergey Nikitin <sergey.nikitin@oktet.tech>